MENU_TITLE = "MAIN MENU"
PARSE_TITLE = "PARSE TEXT FILES"
COMP_TITLE = "BUILD DEFAULT COMPARISONS"
CUST_TITLE = "BUILD CUSTOM COMPARISONS"

MENU_LABEL = "SELECT YOUR DESIRED OPERATION"
PARSE_LABEL = "PARSING TEXT FILES"
COMP_LABEL = "SELECT YOUR DESIRED OPERATION"
CUST_LABEL = "SELECT YOUR DESIRED OPERATION"

MENU_OPTION_0 = "PARSE TEXT FILES"
MENU_OPTION_1 = "BUILD DEFAULT COMPARISONS"
MENU_OPTION_2 = "BUILD CUSTOM COMPARISONS"
MENU_OPTION_3 = "RESET APP"
MENU_OPTION_4 = "EXIT APP"

COMP_OPTION_0 = "BUILD WORD COMPARISONS"
COMP_OPTION_1 = "BUILD LEMMA COMPARISONS"
COMP_OPTION_2 = "BUILD POS COMPARISONS"

BUILD = "BUILD COMPARISONS"
CUST_OPTION_0 = ""


RETURN = "RETURN TO MENU"


ERROR_PARSED = "MUST BUILD PARSED DATASETS FIRST."